on:
  push:
    branches:
      - main
      - "features/***"
  pull_request:
  schedule:
    - cron: 0 8 * * 0-6

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Show hello message
        run: echo "Hello, world!"
